### ISSUE TITLE
Empty or nearly empty wheel on Pypi make import pygeomag fails

### ISSUE THREAD

**Issue by ThomasG77** [boxpet/pygeomag#17]
When I install pygeomag with `pip install pygeomag`, it does install something. The issue is when I try to import pygeomag, it does not find the module. It seems to be related to wheel with nearly empty content.
Looking at https://pypi.org/project/pygeomag/#files, downloading the wheel and inspecting it contents, we see it does not contain any Python files. I suppose it's where the issue lies when importing.

**Comment by justmobilize** [comment]
@ThomasG77 well that's what happens when a file doesn't get committed. Sorry about that.

Pushed a new version `1.0.1`. You can just run `pip install --upgrade pygeomag` and it should all work.

I tested and it worked, but would love a double check before I post the release.
