### ISSUE TITLE
Updating pygeomag for use after 2025?

### ISSUE THREAD

**Issue by hydroscopex** [boxpet/pygeomag#22]
Hi,

First of all, thanks for this very useful library!

I've just ran into a pontential issue when accidently computing magnetic variation values for a date in 2025.

It raises  the following exception :

`ValueError: Time extends beyond model 5-year life span`

This got me wondering if there was any plan for updating the library for use after the new year? Do you need NOAA/NCEI to provide updated data?

Cheers,

**Comment by justmobilize** [comment]
Hey!

You are quite welcome. I mostly did this for myself, but wanted to share.

First, you can pass in `allow_date_outside_lifespan` to `calculate` if you want to get the approximate value for a future date:
```py
result = geo_mag.calculate(80, 0, 0, 2026.0, allow_date_outside_lifespan=True)
```

Second, yes - as soon as a new model is released on [NOAA](https://www.ncei.noaa.gov/products/world-magnetic-model), I'll get a release right out. They updated internal code on `Dec. 10, 2019` for 2020, so I'm guessing it won't be until late 2024 (which is kinda annoying... but is what it is)

**Comment by hydroscopex** [comment]
Ok thanks `allow_date_outside_lifespan=True` does the trick for me!

And it's great to know you'll be updating the code once NOAA updates theirs.

Thanks again for this library!

**Comment by justmobilize** [comment]
Quite welcome. Please let me know if you have any other feedback!

**Comment by justmobilize** [comment]
@hydroscopex just wanted to follow up and say that on the [WMM site](https://www.ncei.noaa.gov/products/world-magnetic-model) they have updated and are releasing the new model on December 17, 2024. So I should get a release out a few days after.
